Apply example_ynh and upgrade to 10.8.1
YunoHost-Apps/jellyfin_ynh pull request #111
Opened 2022-07-20 15:49 UTC by yalh76

## Solution

- *Apply example_ynh*

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2022-07-20 15:49 UTC, yalh76 commented
!testme

2022-07-20 21:08 UTC, yalh76 commented
@tituspijean  do we merge or do we wait for #108 ?

2022-07-23 17:31 UTC, tituspijean commented
!testme

2022-07-24 07:05 UTC, tituspijean requested changes

2022-07-24 07:05 UTC, tituspijean commented on scripts/restore
> +ynh_script_progression --message="Restoring the logrotate configuration..." --time --weight=1
```suggestion
ynh_script_progression --message="Restoring the logrotate configuration..." --weight=1
```

2022-07-24 07:06 UTC, tituspijean approved these changes

2022-07-24 07:06 UTC, merged